/*********************************************************************************/
/************ THIS FILE IS GENERATED BY AWTK DESIGNER, DO NOT MODIFY *************/
/*********************************************************************************/
#include "awtk.h"
#include "../res/assets.inc"

extern ret_t application_init(void);

extern ret_t application_exit(void);

#undef TK_ENABLE_CONSOLE
#define TK_ENABLE_CONSOLE()
#define APP_TYPE APP_DESKTOP

#include "awtk_main.inc"
